---
title: "actdatos"
author: "actdatos"
date: '2022-09-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 1

Definimos la función $h(x)=\frac{1}{\sqrt(x)}$, notemos que $h'(x)=-\frac{1}{2x^{3/2}}$. Ahora con el teorema del método Delta vamos a demostrar que si $\sigma_{y}\propto [\mathbb{E}(y)]^{3}$, la transformación $Y=h(y)$ para la variable $y$ estabiliza la varianza. Con esto solo desarrollamos lo siguiente:

$Var(h(y))\approx (h'(\mu_{y}))^2\sigma^{2}_{y}=[-1/(2(\mu_{y})^{3/2})]^2\sigma^{2}_{y}=\frac{\sigma_{y}^2}{4\mu_{y}^3}\propto \frac{\mu_{y}^{3}}{4\mu_{y}^3}=\frac{1}{4}$

Con esto último, hemos demostrado que la $\sigma_{y}$ es proporcional a una constante.


## Ejercicio 2


A continuación, demostraremos que la transformación Box-Cox(como función de $\lambda$) es continua en $\lambda=0$, para esto bastará demostrar que $\lim_{\lambda\to 0}y(\lambda)=y(0)$, esto es quivalente a demostrar que $\lim_{\lambda\to 0}\frac{y^{\lambda}-1}{\lambda(\dot{y})^{\lambda-1}}=\dot{y}\log{y}$. Con lo cual, procedemos a desarrollar aplicando L'Hopital (teniendo en cuenta que se cumplen las condiciones):

$\lim_{\lambda\to 0}\frac{y^{\lambda}-1}{\lambda(\dot{y})^{\lambda-1}}=\lim_{\lambda\to 0}\frac{y^{\lambda}\log{y}}{\lambda(\dot{y})^{\lambda-1}+\lambda(\dot{y})^{\lambda-1}\log{\dot{y}}}=\dot{y}\log{y}$









