---
title: "lista2"
output: html_document
date: '2022-08-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cargamos archivo y librerías

```{r setup, include=FALSE}

rm(list=ls())

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)

```


```{r paged.print=FALSE}
file <- data.frame(read.table("lista02.dat",skip = 1) )
glimpse(file)
summary(file)

```
## Exploración

```{r paged.print=FALSE}
numNA<-sum(is.na(file))

cat(paste("Hay ",numNA,"NA de la forma usual \n"))

cat(paste("Revisaremos si hay **NA** artificiales:  \n"))

file[which(file == "<NA>",arr.ind = TRUE)[,1],]

file[which(file == "NA",arr.ind = TRUE)[,1],]
```
## Transformación de variables

```{r}

for (i in c(1,2,3,4,5,6,7,8.10)){
  
  file[,i] <- as.double(file[,i])
}
glimpse(file)
  
```


## Regresión lineal simple

```{r}

mod1 <- lm(V7 ~ V10, data=file)
print(mod1)
plot(mod1)

```
```{r}
plot(file$V10,file$V7)
abline(mod1)
abline(h=0, lty=2)
```
 
```{r}
summary(mod1)
anova(mod1)
```
```{r}

```
 
